# Generated by Django 2.1.7 on 2019-04-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=' ', max_length=20)),
                ('title', models.IntegerField(default=0)),
            ],
        ),
    ]
